version: '3'
services: 
  mongodb-server:
    image: 'mongo'
    ports:
      - '27017:27017'
  client:
    build: .
    environment:
      - API_SERVER_URI=http://client:8082/
      - MONGO_URI=mongodb://mongodb-server:27017/
    links:
      - mongodb-server
    ports:
      - "8082:8082"
    restart: on-failure